apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${APP_NAME}-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: pod-${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_ARTIFACT_ID}
          image: "${TARGET_REPO}/${TARGET_WORKSPACE}/${APP_ARTIFACT_ID}:${TAG}"
          imagePullPolicy: Always
          env:
          - name: VCAP_SERVICES
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-vcap-services
                key: vcap
          livenessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 20
            periodSeconds: 60
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}-vcap-services
type: Opaque
data:
  vcap: ${VCAP}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  labels:
    app: ${APP_NAME}
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
  ports:
   - protocol: TCP
     port: 9080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APP_NAME}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ${INGRESS}
    http:
      paths:
      - path: /
        backend:
          serviceName: ${APP_NAME}-service
          servicePort: 9080
